{{- define "base-app.pod.containers" }}
{{- range $container := .Values.pod.containers }}
- name: {{ $container.name }}
  image: {{ $container.image }}
  imagePullPolicy: {{ $container.imagePullPolicy | default "Always" }}
  {{- if $container.command }}
  command:
{{ toYaml $container.command | indent 4 }}
  {{- end }}
  {{- if $container.command }}
  args: 
{{ toYaml $container.args | indent 4 }}
  {{- end }}
  {{- if $container.workingDir }}
  workingDir: {{ $container.workingDir }}
  {{- end }}
  {{- if $container.ports }}
  ports:
    {{- range $port := $container.ports }}
    - containerPort: {{ $port.containerPort }}
      name: {{ $port.name }}
      protocol: {{ $port.protocol }}
    {{- end }}
  {{- end }}
  {{- if $container.env }}
  env:
{{ toYaml $container.env | indent 4 }}
  {{- end }}
  {{- if $container.envFrom }}
  envFrom:
{{ toYaml $container.envFrom | indent 4 }}
  {{- end }}
  {{- if $container.volumeMounts }}
  volumeMounts:
{{ toYaml $container.volumeMounts | indent 4 }}
  {{- end }}
  {{- if $container.resources }}
  resources:
{{ toYaml $container.resources | indent 4 }}
  {{- end }}
  {{- if $container.livenessProbe }}
  livenessProbe:
{{ toYaml $container.livenessProbe | indent 4 }}
  {{- end }}
  {{- if $container.readinessProbe }}
  readinessProbe:
{{ toYaml $container.readinessProbe | indent 4 }}
  {{- end }}
  {{- if $container.startupProbe }}    
  startupProbe:
{{ toYaml $container.startupProbe | indent 4 }}
  {{- end }}
  {{- if $container.securityContext }}    
  securityContext:
{{ toYaml $container.securityContext | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}