{{- define "base-app.pod" }}
metadata:
  labels:
    {{- include "base-app.common-labels" . | indent 4 }}
  {{- if .Values.pod }}
  {{- if .Values.pod.labels }}
  {{- range $key, $val := .Values.pod.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.pod.annotations }}
  annotations:
  {{- range $key, $val := .Values.pod.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
spec:
  containers:
    {{- include "base-app.pod.containers" . | indent 4 }}
  {{- if .Values.pod }}
  {{- if .Values.pod.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.pod.nodeSelector | indent 4 }}
  {{- end }}
  {{- if .Values.pod.tolerations }}
  tolerations:
{{ toYaml .Values.pod.tolerations | indent 4 }}
  {{- end }}
  restartPolicy: {{ .Values.pod.restartPolicy | default "Always" }}
  {{- if .Values.pod.hostAliases }}
  hostAliases:
{{ toYaml .Values.pod.hostAliases | indent 4 }}
  {{- end }}
  {{- if .Values.pod.serviceAccount }}
  serviceAccountName: {{ .Values.pod.serviceAccount }}
  {{- end }}
  {{- if .Values.pod.imagePullSecrets }}
  imagePullSecrets:
{{ toYaml .Values.pod.imagePullSecrets | indent 4 }}
  {{- end }}
  {{- if .Values.pod.volumes }}
  volumes:
{{ toYaml .Values.pod.volumes | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}