apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- template "mychart.labels" | indent 4  }}
  annotations:
    foo: bar
spec:
  selector:
    matchLabels:
      foo: bar
  replicas: 0
  strategy:
    type: Recreate/RollingUpdate
    rollingUpdate:
      maxSurge: 0/""
      maxUnavailable: 0/""
  revisionHistoryLimit: 0
  template:
    <pod template>

