apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "base-app.common-labels" . | indent 4 }}
  {{- range $key, $val := .Values.deployment.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- if .Values.deployment.annotations }}
  annotations:
  {{- range $key, $val := .Values.deployment.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.deployment.replicas | default 1 }}
  strategy:
    type: {{ .Values.deployment.strategy.type | default "RollingUpdate" | quote }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge | default "25%" | quote }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable | default "25%" | quote }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit | default 10 }}
  template:
    {{- include "base-app.pod" . | indent 4 }}

