{{- if .Values.secrets }}
{{- range $secret := .Values.secrets }}
---
apiVersion: core/v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "base-app.common-labels" $ | indent 4 }}
  {{- if $secret.labels }}
  {{- range $key, $val := $secret.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  {{- if $secret.annotations }}
  annotations:
  {{- range $key, $val := $secret.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- if $secret.immutable }}
immutable: {{ $secret.immutable }}
{{- end }}
{{- if $secret.stringData }}
stringData:
{{- range $key, $val := $secret.stringData }}
  {{ $key }}: |
{{ $val | b64enc | indent 4}}
{{- end }}
{{- end }}
{{- if $secret.data }}
data:
{{- range $key, $val := $secret.data }}
  {{ $key }}: |
{{ $val | b64enc | indent 4}}
{{- end }}
{{- end }}
type: {{ $secret.type | default "Opaque" }}
{{- end }}
{{- end }}