
deployment:
#  labels:
#    foo: bar
#    foo2: bar2
#  annotations:
#    annFoo: annBar
#    annFoo2: annBar2
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 26%
#      maxUnavailable: 26%
#  revisionHistoryLimit: 11
  replicas: 2

pod:
#  labels:
#    podFoo: podFoo
#    podFoo2: podFoo2
#  annotations:
#    podAnnFoo: podAnnFoo
#    podAnnFoo2: podAnnFoo2
  
#  nodeSelector:
#    selectorFoo: selectorBar
#  tolerations:
#    - key: ""
#      operator: ""
#      value: ""
#      effect: ""

#  restartPolicy: Never
#  hostAliases:
#    - hostnames:
#        - name1.com
#        - name2.com
#      ip: "8.8.8.8"

#  serviceAccount: amazingServiceAccount

#  imagePullSecrets:
#    - name: dockerhub.com
  
#  volumes:
#    - name: "volumen1"
#      persistentVolumeClaim:
#        claimName: "pvcname"
#        readOnly: true
#    - name: "volumen2"
#      configMap:
#        name: amazingCm
#        optional: false
#        defaultMode: 0777
#        items:
#          - key: ""
#            path: ""
#            mode: 0777
#    - name: ""
#      secret:
#        secretName: ""
#        optional: bool
#        defaultMode: 0777
#        items:
#          - key: ""
#            path: ""
#            mode: 0777

  containers:
    - name: nginx
      image: nginx
#      imagePullPolicy: Always
#      command:
#        - ""
#      args:
#        - ""
#      workingDir: /root
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
#      env:
#        containerFoo: containerBar
#      volumeMounts:
#        - mountPath: ""
#          name: ""
#          readOnly: bool
#          subPath: ""
#        - mountPath: ""
#          name: ""
#          readOnly: bool
#          subPathExpr: ""
#      resources:
#        requests:
#          cpu: 50m
#          memory: 128Mi
#        limits:
#          cpu: 250m
#          memory: 512Mi
#      readinessProbe: # the same for readiness and startup
#        httpGet:
#          port: http
#          httpHeaders:
#            - name: ""
#              value: ""
#          path: /to/path
#          scheme: http
#          initialDelaySeconds: 10
#          terminationGracePeriodSeconds: 0
#          periodSeconds: 5
#          timeoutSeconds: 5
#          failureThreshold: 5
#          successThreshold: 5
#          grpc:
#            port: 0
#            service: ""
#      securityContext:
#        runAsUser: 0
#        runAsNonRoot: bool
#        privileged: bool

service:
  type: ClusterIP 
#  type: NodePort
#  labels:
#    foo: bar
#  annotations:
#    foo: bar
  ports:
    - name: http
      port: 8080
      targetPort: http
#    - name: https
#      port: 443
#      targetPort: https
#      nodePort: 35012

ingress:
#  labels:
#    foo: bar
#  annotations:
#    foo: bar
#  defaultBackend:
#    name: ""
#    port: 0
#  className: nginx
  rules:
    - host: "example.com"
      servicePortName: http
#    - path: "/test"
#      pathType: "Exact"
#      servicePortName: http
#      servicePort: 8080
#  tls:
#    hosts:
#      - example.com
#    secretName: secret-name

